# Create a program that will play the 'cows and bulls' game with the user. The game works
# like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every
# digit that the user guessed correctly in the correct place, they have a 'cow'. For
# every digit the user guessed correctly in the wrong place is a 'bull.' Every time the
# user makes a guess, tell them how many 'cows' and 'bulls' they have. Once the user
# guesses the correct number, the game is over. Keep track of the number of guesses the
# user makes throughout the game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like
# this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull

# Until the user guesses the number.


import random
number = str(random.randint(1000,9999)) #random 4 digit number
print "Welcome to the cows and bulls game!"
lst = []
for letter in number:
    lst.append(letter)

user_num = 0
cows = 0
bulls = 0


while number != user_num:
    user_num = raw_input("Guess a 4-digit number or type exit to leave: ")
    if user_num == 'exit':
        print "Game over"
        break
    user_lst = []
    for item in user_num:
        user_lst.append(item)
    counter = 0
    for item in lst:
            if item == user_lst[counter]:
                user_lst[counter] = "a"
                cows = cows + 1
            counter = counter + 1
    counter = 0
    bull_lst = []
    for item in lst:
        if item in user_lst:
            if item not in bull_lst:
                bull_lst.append(item)
            bulls = len(bull_lst)
    print "cows: ", cows
    print "buls: ", bulls




                
